import Observation
import SwiftData

/// Macro-free SwiftData support for command-line builds where Apple's
/// SwiftDataMacros plugin is not shipped with the macOS Command Line Tools.
/// The runtime field names intentionally match the fields generated by @Model.
protocol NovelForgePersistentModel: PersistentModel {
    var novelForgeObservationRegistrar: ObservationRegistrar { get }
}

extension NovelForgePersistentModel {
    func observeAccess<Member>(keyPath: KeyPath<Self, Member>) {
        novelForgeObservationRegistrar.access(self, keyPath: keyPath)
    }

    func observeMutation<Member, MutationResult>(
        keyPath: KeyPath<Self, Member>,
        _ mutation: () throws -> MutationResult
    ) rethrows -> MutationResult {
        try novelForgeObservationRegistrar.withMutation(of: self, keyPath: keyPath, mutation)
    }
}

@propertyWrapper
struct PersistedValue<Value: Codable> {
    private var initialValue: Value

    init(wrappedValue: Value) {
        self.initialValue = wrappedValue
    }

    @available(*, unavailable, message: "PersistedValue requires a NovelForgePersistentModel owner")
    var wrappedValue: Value {
        get { initialValue }
        set { initialValue = newValue }
    }

    static subscript<Owner: NovelForgePersistentModel>(
        _enclosingInstance owner: Owner,
        wrapped wrappedKeyPath: ReferenceWritableKeyPath<Owner, Value>,
        storage _: ReferenceWritableKeyPath<Owner, Self>
    ) -> Value {
        get {
            owner.observeAccess(keyPath: wrappedKeyPath)
            return owner.getValue(forKey: wrappedKeyPath)
        }
        set {
            if owner.modelContext == nil {
                owner.persistentBackingData.setValue(forKey: wrappedKeyPath, to: newValue)
                return
            }
            owner.observeMutation(keyPath: wrappedKeyPath) {
                owner.setValue(forKey: wrappedKeyPath, to: newValue)
            }
        }
    }
}

@propertyWrapper
struct PersistedToOne<Related: PersistentModel> {
    private var initialValue: Related?

    init(wrappedValue: Related?) {
        self.initialValue = wrappedValue
    }

    @available(*, unavailable, message: "PersistedToOne requires a NovelForgePersistentModel owner")
    var wrappedValue: Related? {
        get { initialValue }
        set { initialValue = newValue }
    }

    static subscript<Owner: NovelForgePersistentModel>(
        _enclosingInstance owner: Owner,
        wrapped wrappedKeyPath: ReferenceWritableKeyPath<Owner, Related?>,
        storage _: ReferenceWritableKeyPath<Owner, Self>
    ) -> Related? {
        get {
            owner.observeAccess(keyPath: wrappedKeyPath)
            return owner.getValue(forKey: wrappedKeyPath)
        }
        set {
            if owner.modelContext == nil {
                owner.persistentBackingData.setValue(forKey: wrappedKeyPath, to: newValue)
                return
            }
            owner.observeMutation(keyPath: wrappedKeyPath) {
                owner.setValue(forKey: wrappedKeyPath, to: newValue)
            }
        }
    }
}

@propertyWrapper
struct PersistedToMany<Related: PersistentModel> {
    private var initialValue: [Related]?

    init(wrappedValue: [Related]?) {
        self.initialValue = wrappedValue
    }

    @available(*, unavailable, message: "PersistedToMany requires a NovelForgePersistentModel owner")
    var wrappedValue: [Related]? {
        get { initialValue }
        set { initialValue = newValue }
    }

    static subscript<Owner: NovelForgePersistentModel>(
        _enclosingInstance owner: Owner,
        wrapped wrappedKeyPath: ReferenceWritableKeyPath<Owner, [Related]?>,
        storage _: ReferenceWritableKeyPath<Owner, Self>
    ) -> [Related]? {
        get {
            owner.observeAccess(keyPath: wrappedKeyPath)
            return owner.getValue(forKey: wrappedKeyPath)
        }
        set {
            if owner.modelContext == nil {
                owner.persistentBackingData.setValue(forKey: wrappedKeyPath, to: newValue)
                return
            }
            owner.observeMutation(keyPath: wrappedKeyPath) {
                owner.setValue(forKey: wrappedKeyPath, to: newValue)
            }
        }
    }
}
